# Generated by Django 2.2.7 on 2019-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='number_guard',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
