# Generated by Django 2.2.7 on 2019-11-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (2, 'Firm'), (3, 'admin')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='bodyguard_api.Role'),
        ),
    ]
