# Generated by Django 2.2.7 on 2019-11-28 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0002_auto_20191128_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='number_guard',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
