# Generated by Django 2.2.7 on 2019-11-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0004_auto_20191114_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
