# Generated by Django 2.2.7 on 2019-11-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0005_auto_20191114_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='bodyguard_api.Role'),
        ),
    ]
