# Generated by Django 2.2.7 on 2019-11-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0007_auto_20191114_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
