# Generated by Django 2.2.7 on 2019-11-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0010_auto_20191114_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Firm')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='bodyguard_api.Role'),
        ),
    ]
