# Generated by Django 2.2.7 on 2019-11-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0011_auto_20191115_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
