# Generated by Django 2.2.7 on 2019-11-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0014_auto_20191118_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
