# Generated by Django 2.2.7 on 2019-11-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodyguard_api', '0015_auto_20191119_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(null=True),
        ),
    ]
